[package]
name = "org-roam-protocol-installer"
version = "0.1.0"
edition = "2018"
authors = ["derui <derutakayu@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "~2.27.0"
dirs = "~3.0.2"