name: Build release for platforms
on:
  release:
    types:
      - published
jobs:
  build-for-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install musl target
        run: rustup target add x86_64-unknown-linux-musl
      - name: Build for linux
        run: cargo build --release --target x86_64-unknown-linux-musl
      - run: mv target/x86_64-apple-darwin/release/org-roam-protocol-installer .
      - run: zip org-roam-protocol-installer-x86_64-unknown-linux.zip org-roam-protocol-installer

      - name: Upload Release linux
        id: upload-release-asset-linux
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
        # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: org-roam-protocol-installer-x86_64-unknown-linux.zip
          asset_name: org-roam-protocol-installer-x86_64-unknown-linux.zip
          asset_content_type: application/tar+gzip

  build-for-macos:
    runs-on: macos-10.15
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build for macOS
        run: cargo build --release --target x86_64-apple-darwin
      - run: codesign --force -s - target/x86_64-apple-darwin/release/org-roam-protocol-installer
      - run: xattr -d -r com.apple.quarantine target/x86_64-apple-darwin/release/org-roam-protocol-installer
      - run: mv target/x86_64-apple-darwin/release/org-roam-protocol-installer .
      - run: zip org-roam-protocol-installer-x86_64-apple-darwin.zip org-roam-protocol-installer

      - name: Upload Release macos
        id: upload-release-asset-macos
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
        # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: org-roam-protocol-installer-x86_64-apple-darwin.zip
          asset_name: org-roam-protocol-installer-x86_64-apple-darwin.zip
          asset_content_type: application/tar+gzip
