name: Build release for platforms
on:
  release:
    types:
      - published
jobs:
  build-for-linux:
    runs-on: ubuntu-latest
    container:
      image: joseluisq/rust-linux-darwin-builder:1.54.0
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build for linux
        run: cargo build --release
      - run: tar -czvf org-roam-protocol-installer-x86_64-unknown-linux.tar.gz -C target/x86_64-unknown-linux-musl/release org-roam-protocol-installer

      - name: Upload Release linux
        id: upload-release-asset-linux
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.events.release.upload_url }}
        # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: org-roam-protocol-installer-x86_64-unknown-linux.tar.gz
          asset_name: org-roam-protocol-installer-x86_64-unknown-linux.tar.gz
          asset_content_type: application/tar+gzip

  build-for-macos:
    runs-on: macos-10.15
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build for macOS
        run: cargo build --release --target x86_64-apple-darwin
      - run: codesign --force -s - target/x86_64-apple-darwin/release/org-roam-protocol-installer
      - run: tar -czvf org-roam-protocol-installer-x86_64-apple-darwin.tar.gz -C target/x86_64-apple-darwin/release org-roam-protocol-installer

      - name: Upload Release macos
        id: upload-release-asset-macos
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.events.release.upload_url }}
        # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: org-roam-protocol-installer-x86_64-apple-darwin.tar.gz
          asset_name: org-roam-protocol-installer-x86_64-apple-darwin.tar.gz
          asset_content_type: application/tar+gzip
